"""Persistence interfaces; adapters may be SQLite, PostgreSQL, or remote stores."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Protocol

from agentgate.domain import Dataset, DatasetVersion, Result, Run, Trace
from agentgate.trace.models import IngestionReport, TraceBatch


@dataclass(frozen=True)
class PendingTraceCorrelation:
    run_id: str
    case_id: str
    invocation_id: str
    trace_id: str
    created_at: datetime


class AgentGateRepository(Protocol):
    def save_dataset(self, dataset: Dataset) -> None: ...
    def save_dataset_with_draft(
        self, dataset: Dataset, draft: DatasetVersion
    ) -> None: ...
    def get_dataset(self, dataset_id: str) -> Dataset | None: ...
    def list_datasets(self, include_archived: bool = False) -> list[Dataset]: ...
    def save_dataset_version(self, version: DatasetVersion) -> None: ...
    def get_dataset_version(self, dataset_id: str, version: int) -> DatasetVersion | None: ...
    def get_latest_dataset_version(self, dataset_id: str) -> DatasetVersion | None: ...
    def get_dataset_draft(self, dataset_id: str) -> DatasetVersion | None: ...
    def list_dataset_versions(
        self, dataset_id: str, include_draft: bool = True
    ) -> list[DatasetVersion]: ...
    def delete_dataset_draft(self, dataset_id: str) -> None: ...
    def publish_dataset_draft(
        self, dataset_id: str, published_at: datetime
    ) -> DatasetVersion: ...

    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, limit: int = 50) -> list[Run]: ...
    def save_trace(self, trace: Trace) -> None: ...
    def get_trace(self, run_id: str, case_id: str) -> Trace | None: ...
    def list_traces(self, run_id: str) -> list[Trace]: ...
    def ingest_trace_batch(
        self, batch: TraceBatch
    ) -> IngestionReport: ...
    def get_trace_revision(
        self, run_id: str, case_id: str, revision: int
    ) -> Trace | None: ...
    def evaluate_trace_completeness(
        self, run_id: str, case_id: str, now: datetime
    ) -> Trace: ...
    def expire_trace(self, run_id: str, case_id: str, now: datetime) -> Trace: ...
    def expire_due_traces(self, now: datetime, limit: int = 100) -> tuple[Trace, ...]: ...
    def save_results(self, results: list[Result]) -> None: ...
    def list_results(self, run_id: str) -> list[Result]: ...
    def put_business_state(self, namespace: str, key: str, value: dict) -> None: ...
    def get_business_state(self, namespace: str, key: str) -> dict | None: ...
    def put_pending_trace(
        self, run_id: str, case_id: str, invocation_id: str, trace_id: str
    ) -> None: ...
    def get_pending_trace(self, trace_id: str) -> PendingTraceCorrelation | None: ...
